# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.3.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # scan
  end

  desc "Submit a new InHouse Build to pgyer"
  lane :InHouse do
    ensure_git_status_clean   #确保git状态为clean
    # git_pull  #拉取git
    # increment_build_number
    ipa_path = "/Users/ouyangshanzi/Desktop/FastlaneDemo-" + Time.now.strftime("%Y-%m-%d-%H-%M-%S") #存放ipa、dsym文件的文件夹
    ipa_name = "FastlaneDemo-enterprise.ipa"  #ipa文件名
    ipa_destination = ipa_path + "/" + ipa_name #ipa文件路径
    gym(
      scheme: "FastlaneDemo", #
      configuration: "Release", #打包方式 Release、Debug
      export_method: "enterprise",  #adhoc、debug、enterprise、appstore
      clean: true,  #打包前先clean，减小包大小和一些库的编译
      output_directory: ipa_path, #ipa导出文件夹
      output_name: ipa_name #ipa导出的文件名
    )
    # snapshot
    sh "ipa distribute:pgyer -f "+ ipa_destination +" -u c95b59a6e3044f5f3ba093e3b9272521 -a 0e8952c4f7e6c5630c0299a5249d728f"
    # sh "ipa distribute:fir -f "+ ipa_destination +" -u e8dadc58747884132f02e861bac04462 -a 56d6b3f6e75e2d04e1000010"
    # sh "ipa distribute:sftp -f "+ ipa_destination +" --host 192.168.10.80 -u dell -p 123456 /测试共享文件夹/iOS版本/4.0.5/ "
  end

  desc "UI automation test"
  lane :do_monkey_test do |options|
    times               = options[:times] || 2
    scheme              = options[:scheme]
    project             = options[:project]
    device_udid         = options[:device_udid]
    device_type         = options[:device_type]
    script              = options[:script]
    report_output_path  = options[:report_output_path]

    git_pull
    xcodebuild(
      scheme: scheme,
      arch: 'x86_64',
      sdk: 'iphonesimulator10.2',
      configuration: 'Debug'
    )
    app_path = get_debug_app_path(
      scheme: scheme,
      project: project
    )
    (1..times.to_i).each do |i|
      # 使用ios-sim命令安装app到模拟器，如果是真机的话，则使用ios-deploy
      install_app_on_simulator(
        divice_type: device_type,
        app_path: app_path
      )
      sleep(30)
      instruments_ui_automation(
        device: device_udid,
        app_path: app_path,
        report_output_path: report_output_path,
        script: script
      )
    end

  end

  # desc "Runs all the tests"
  # lane :test do
  #   scan
  # end

  # desc "Submit a new Beta Build to Apple TestFlight"
  # desc "This will also make sure the profile is up to date"
  # lane :beta do
  #   # match(type: "appstore") # more information: https://codesigning.guide
  #   gym(scheme: "FastlaneDemo") # Build your app - more options available
  #   pilot
  #
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here (run `fastlane actions`)
  # end

  # desc "Deploy a new version to the App Store"
  # lane :release do
  #   # match(type: "appstore")
  #   # snapshot
  #   gym(scheme: "FastlaneDemo") # Build your app - more options available
  #   deliver(force: true)
  #   # frameit
  # end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
